version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: PgDb!2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    environment:
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: PgDb!2025
      
      # Keycloak admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: KcAdm!n2025
      
      # Keycloak configuration
      KC_HOSTNAME: keycloak.nilosolutions.com
      KC_HTTP_PORT: 8080
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      
      # Development mode
      KC_LOG_LEVEL: INFO
      
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./themes:/opt/keycloak/themes
    ports:
      - "8085:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network
    restart: unless-stopped
    command: 
      - start-dev
      - --import-realm

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge